sudo: required

language: javascript

services:
  - docker

before_install:
- docker pull golbie/ubuntu-docker-protractor:0.0.1

before_script:
- npm install -g @angular/cli
- npm install
- ng build

script:
- docker run --rm -v $TRAVIS_BUILD_DIR/angular2-app-under-test:/project golbie/ubuntu-docker-protractor:0.0.1
- npm run test