version: 2.0
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/angular2-app-under-test

    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker run --rm -v ~/angular2-app-under-test:/project golbie:ubuntu-docker-protractor