version: 2.0
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/app

    steps:
      - checkout

      - run: |
          pwd
          ls -la
          docker pull golbie/ubuntu-docker-protractor:0.0.1
          docker run --rm -v ~/app/angular2-app-under-test:/project golbie/ubuntu-docker-protractor:0.0.1