version: 2.0
jobs:
  build:
    docker:
      - image: golbie/ubuntu-docker-protractor:0.0.1

    working_directory: ~/angular2-app-under-test

    steps:
      - checkout

      - run: |
          sudo docker run --rm -v ~/angular2-app-under-test:/project golbie:ubuntu-docker-protractor